"""update_user model

Revision ID: 456affcd6c43
Revises: f299d6ad1000
Create Date: 2023-06-05 12:36:32.846112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456affcd6c43'
down_revision = 'f299d6ad1000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###
